### ISSUE TITLE
유지선 - 사전 과제 제출

### ISSUE THREAD

**Issue by ujiseon** [Kim-jy0819/wanted-pre-onboarding-challenge-data#54]
https://github.com/ujiseon/wanted-pre-onboarding-challenge-data.git

깃허브를 처음써봐서 잘 모르겠습니다ㅜㅜ 이렇게 하는게 맞을까요...

**Comment by jinyoung-kim-dinnercoding** [comment]
네 ㅎㅎ 잘하셨습니다!
